name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"
    
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Build (Release)
      run: dotnet build . --configuration Release -p:Version=$GitVersion_SemVer
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      if: github.event_name == 'push'
      with:
        path: ./dist