name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"
    
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Authenticate for GitHub Packages
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name deca-github "https://nuget.pkg.github.com/decaprime/index.json"

    - name: Build (Release)
      run: dotnet build . --configuration Release -p:Version=$GitVersion_SemVer
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      if: github.event_name == 'push'
      with:
        path: ./dist
        
    - name: GH Release
      # You may pin to the exact commit or the version.
      # uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
      uses: softprops/action-gh-release@v0.1.14
      with:
        body: Automatic pre-release for $GitVersion_ShortSha
        name: $GitVersion_FullSemVer - $GitVersion_ShortSha
        files: ./dist/LeadAHorseToWater.dll
        fail_on_unmatched_files: true
        generate_release_notes: true 
        draft: true
        prerelease: true